version: "3.6"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
#  applist:
#    image: jwilder/nginx-proxy
#    ports:
#      - '80:80'
#    environment:
#      DEFAULT_HOST: "webproject.local"
#    volumes:
#      - '/var/run/docker.sock:/tmp/docker.sock'
#    restart: always

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    network_mode: "host"
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '80:80/tcp'
      - "443:443/tcp"
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `mkdir var-log; touch ./var-log/pihole.log` first unless you like errors
      - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - CAP_NET_ADMIN
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    environment:
      ServerIP: 192.168.1.25
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.webproject.lan
      VIRTUAL_PORT: 80
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      DNSSEC: "True"
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      # - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using jwilder
      - 'webproject.lan:192.168.1.15'
      - 'pihole pihole.webproject.lan:192.168.1.25'
    restart: always
    
